apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
spec:
  type: LoadBalancer
  selector:
    app: welcome-app
  ports:
  - protocol: TCP
    port: 80       # Puerto del balanceador de carga
    targetPort: 8080 # Puerto del contenedor